name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

concurrency:
  group: Build ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests

    strategy:
      matrix:
        api-level: [36]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install php dependencies
        uses: monicahq/workflows/.github/actions/php@v4
        with:
          php-version: 8.4
        env:
          COMPOSER_AUTH_JSON: |
            {
              "http-basic": {
                "nativephp.composer.sh": {
                  "username": "${{ secrets.NATIVEPHP_USERNAME }}",
                  "password": "${{ secrets.NATIVEPHP_PASSWORD }}"
                }
              }
            }

      - name: Build javascript assets
        uses: monicahq/workflows/.github/actions/js@v4
        with:
          node-version: 22

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Run AVD."

    # Prepare
      - name: Prepare environment
        run: cp tests/.env.ci.sqlite .env

      - name: Generate key
        run: php artisan key:generate

      - name: Setup nativephp
        run: |
          {
            echo "NATIVEPHP_APP_ID=com.monicahq.geller"
            echo "NATIVEPHP_DEVELOPMENT_TEAM=${{ secrets.NATIVEPHP_DEVELOPMENT_TEAM }}"
            echo "APP_INSTANCE_URL=https://rachel.monicahq.com"
          } >> .env

      - name: Cache nativephp files
        uses: actions/cache@v4
        with:
          path: nativephp/android/
          key: ${{ runner.os }}-nativephp-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-nativephp-${{ hashFiles('**/composer.lock') }}
            ${{ runner.os }}-nativephp-

      - name: Install nativephp
        run: php artisan native:install --force

      - name: Build version
        run: php artisan native:run android --build=debug --no-tty
